import React, { useState, useEffect } from "react";
import CommentCard from "./CommentCard";
import commentAvatar from "../assets/profile-default-icon.png";
import {
  getCommentsForPost,
  createComment,
  likeComment,
} from "../services/comment";
import { Comment as CommentModel } from "../models/Comment";

interface CommentsSectionProps {
  postId: number;
  userId: number;
}

const CommentsSection = ({ postId, userId }: CommentsSectionProps) => {
  const [comments, setComments] = useState<CommentModel[]>([]);
  const [newComment, setNewComment] = useState<string>("");

  useEffect(() => {
    const fetchComments = async () => {
      try {
        const initialComments = await getCommentsForPost(postId, userId);
        setComments(initialComments);
      } catch (error) {
        console.error("Error fetching comments:", error);
      }
    };

    fetchComments();
  }, [postId, userId]);

  const handleAddComment = async () => {
    if (newComment.trim() !== "") {
      try {
        const newCommentData: CommentModel = {
          commentId: 0, // Comment ID will be generated by the server
          userId,
          postId,
          text: newComment,
          created_at: "",
          updated_at: "",
          likes: 0,
        };
        const addedComment = await createComment(newCommentData);
        setComments([...comments, addedComment]);
        setNewComment("");
      } catch (error) {
        console.error("Error adding comment:", error);
      }
    }
  };

  const handleLikeComment = async (commentId: number) => {
    try {
      const updatedComment = await likeComment(commentId, userId);
      setComments(
        comments.map((comment) =>
          comment.commentId === updatedComment.commentId
            ? updatedComment
            : comment
        )
      );
    } catch (error) {
      console.error("Error liking comment:", error);
    }
  };

  return (
    <div>
      <div className="input-group mt-3">
        <input
          type="text"
          className="form-control"
          value={newComment}
          onChange={(e) => setNewComment(e.target.value)}
          placeholder="Add a comment"
        />
        <div className="input-group-append">
          <button
            className="btn btn-outline-secondary"
            onClick={handleAddComment}
          >
            Comment
          </button>
        </div>
      </div>

      <h6 className="mt-4">Comments</h6>
      <div className="mb-3">
        {comments.map((comment) => (
          <CommentCard
            key={comment.commentId}
            {...comment}
            avatarUrl={commentAvatar} // Ensure default avatar
            onLike={() => handleLikeComment(comment.commentId)}
          />
        ))}
      </div>
    </div>
  );
};

export default CommentsSection;
